// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-yhaKCOXunXliBu7cYx23MGGX_yXwv4w',
    appId: '1:502970115138:web:7f6a16586863399dd879db',
    messagingSenderId: '502970115138',
    projectId: 'cryptoapp-8734b',
    authDomain: 'cryptoapp-8734b.firebaseapp.com',
    databaseURL: 'https://cryptoapp-8734b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cryptoapp-8734b.appspot.com',
    measurementId: 'G-80JGSZ432M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu_IjGHdmcIplOFCwHoiBdI3uxyC02eH8',
    appId: '1:502970115138:android:6ccb7ad99a220c95d879db',
    messagingSenderId: '502970115138',
    projectId: 'cryptoapp-8734b',
    databaseURL: 'https://cryptoapp-8734b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cryptoapp-8734b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmFmm-dh1OvNx-0sI_JBD8YPiJZ8eM6mE',
    appId: '1:502970115138:ios:9099b702a80e4edfd879db',
    messagingSenderId: '502970115138',
    projectId: 'cryptoapp-8734b',
    databaseURL: 'https://cryptoapp-8734b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cryptoapp-8734b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
